# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20170517_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='no_of_floors',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='treasury_receipt_number',
            field=models.IntegerField(),
        ),
    ]
