# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20170517_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_of_registration',
            field=models.DateField(auto_now=True),
        ),
    ]
