# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20170520_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_of_registration',
            field=models.DateField(default='01/01/2017'),
        ),
    ]
