# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20170520_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='name_of_approving_officer',
            new_name='approving_officer',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='name_of_charting_officer',
            new_name='charting_officer',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='name_of_inspector',
            new_name='inspector',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='location_of_proposal',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='name_of_recommending_officer',
            new_name='recommending_officer',
        ),
    ]
