# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 20:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_auto_20170523_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='no_of_floors',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='registration_plan_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='sn',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='treasury_receipt_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
