# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_auto_20170527_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='treasury_receipt_number',
            field=models.IntegerField(default=0),
        ),
    ]
