# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_application_treasury_receipt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('position', models.CharField(choices=[('Inspector', 'Inspector'), ('Recommending Officer', 'Recommending Officer'), ('Charting Officer', 'Charting Officer'), ('Approving Officer', 'Approving Officer'), ('Others', 'Others')], default='Others', max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='approving_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_approving_officer', to='record.staff'),
        ),
        migrations.AlterField(
            model_name='application',
            name='charting_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_charting_officer', to='record.staff'),
        ),
        migrations.AlterField(
            model_name='application',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_inspector', to='record.staff'),
        ),
        migrations.AlterField(
            model_name='application',
            name='recommending_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_recommending_officer', to='record.staff'),
        ),
        migrations.AlterField(
            model_name='application',
            name='treasury_receipt_number',
            field=models.CharField(max_length=25),
        ),
    ]
